sudo: false
cache: bundler
rvm:
  - "1.9.3"
  - "2.1.5"
  - "2.2.4"
  - "2.3.3"
  - jruby
  #- rbx-2.2.3
gemfile:
  #- gemfiles/rails_2.3.gemfile # only test for ruby < 2.0
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_2.3.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/rails_4.0.no-active-record.gemfile
      env: SKIP_ACTIVE_RECORD=true
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_5.0.gemfile
script: "bundle exec rake spec"
