sudo: false
cache: bundler

before_install:
  - gem update bundler

rvm:
  - "2.4.4"
  - "2.5.1"
  - "2.6.0"
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

script: "bundle exec rake spec"
